In [23]:
import pandas as pd
import numpy as np
pd.set_option("display.max_columns", None)

In [3]:
data = pd.read_csv("fulldata_05_18_01_P_미용업.csv", encoding="cp949")

C:\Users\ASUS\AppData\Local\Temp\ipykernel_9032\553608778.py:1: DtypeWarning: Columns (11,36) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("fulldata_05_18_01_P_미용업.csv", encoding="cp949")

In [4]:
len(data)

395617

In [5]:
data.columns

Index(['번호', '개방서비스명', '개방서비스아이디', '개방자치단체코드', '관리번호', '인허가일자', '인허가취소일자',
       '영업상태구분코드', '영업상태명', '상세영업상태코드', '상세영업상태명', '폐업일자', '휴업시작일자', '휴업종료일자',
       '재개업일자', '소재지전화', '소재지면적', '소재지우편번호', '소재지전체주소', '도로명전체주소', '도로명우편번호',
       '사업장명', '최종수정시점', '데이터갱신구분', '데이터갱신일자', '업태구분명', '좌표정보(x)', '좌표정보(y)',
       '위생업태명', '건물지상층수', '건물지하층수', '사용시작지상층', '사용끝지상층', '사용시작지하층', '사용끝지하층',
       '의자수', '조건부허가신고사유', '조건부허가시작일자', '조건부허가종료일자', '건물소유구분명', '여성종사자수',
       '남성종사자수', '침대수', '다중이용업소여부', 'Unnamed: 44'],
      dtype='object')

In [6]:
data = data.loc[data["영업상태명"]!='폐업']
len(data)

176675

In [7]:
data["도로명주소_split"] = data["도로명전체주소"].astype("str").apply(lambda x: [_.strip() for _ in x.split(" ") if _.strip() != ''])

In [8]:
data["도로명주소_split"].apply(lambda x: len(x)).max()

18

In [9]:
def optional_index(_list, index):
    try:
        return _list[index]
    except IndexError:
        return None

In [10]:
도로명 = pd.DataFrame({i:data["도로명주소_split"].apply(lambda x: optional_index(x, i)) for i in range(18)})

In [11]:
도로명

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
218942,경기도,양평군,서종면,하문호나룻터길,14,None,None,None,None,None,None,None,None,None,None,None,None,None
218943,서울특별시,노원구,동일로218길,"25,",석창빌딩,1층,103(일부)호,(상계동),None,None,None,None,None,None,None,None,None,None
218944,경기도,평택시,비전2로,"196,",골든프라자-7,206호,(비전동),None,None,None,None,None,None,None,None,None,None,None
218945,울산광역시,중구,종가17길,"41,",101호,(서동),None,None,None,None,None,None,None,None,None,None,None,None
218946,경상남도,창원시,마산합포구,서성로,"43,",가동,106호,"(신포동2가,",삼익아파트),None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395612,광주광역시,남구,회재로1186번길,"29,",18동,103호,"(주월동,",현대아파트상가),None,None,None,None,None,None,None,None,None,None
395613,광주광역시,광산구,신창로,36,"(신창동,미소빌딩",102호(1층)),None,None,None,None,None,None,None,None,None,None,None,None
395614,광주광역시,광산구,수등로258번길,"4-6,",1층,101호,(신가동),None,None,None,None,None,None,None,None,None,None,None
395615,광주광역시,광산구,풍영로,"294-8,",1층,104호,"(장덕동,",고실마을,부영,애시앙),None,None,None,None,None,None,None,None
395616,광주광역시,광산구,월계로,"223-20,",1층,109호,"(쌍암동,",첨단도휘에드가,2차),None,None,None,None,None,None,None,None,None

In [12]:
sorted(도로명[1].astype("str").unique())

['None',
 '가름로',
 '가평군',
 '갈매로',
 '강남구',
 '강동구',
 '강릉시',
 '강북구',
 '강서구',
 '강진군',
 '강화군',
 '거제시',
 '거창군',
 '경산시',
 '경주시',
 '계룡시',
 '계양구',
 '고령군',
 '고성군',
 '고양시',
 '고운서길',
 '고창군',
 '고흥군',
 '곡성군',
 '공주시',
 '과천시',
 '관악구',
 '광명시',
 '광산구',
 '광양시',
 '광주시',
 '광진구',
 '괴산군',
 '구례군',
 '구로구',
 '구리시',
 '구미시',
 '국세청로',
 '국책연구원1로',
 '군산시',
 '군위군',
 '군포시',
 '금남면',
 '금산군',
 '금송로',
 '금정구',
 '금천구',
 '기장군',
 '김제시',
 '김천시',
 '김포시',
 '김해시',
 '나리1로',
 '나성로',
 '나성북1로',
 '나성북로',
 '나주시',
 '남구',
 '남동구',
 '남세종로',
 '남양주시',
 '남원시',
 '남해군',
 '노원구',
 '노을1로',
 '노을3로',
 '노을6로',
 '논산시',
 '누리로',
 '다솜1로',
 '다솜로',
 '다정남로',
 '다정로',
 '다정북로',
 '다정중앙로',
 '단양군',
 '달빛1로',
 '달빛로',
 '달서구',
 '달성군',
 '담양군',
 '당진시',
 '대덕구',
 '대평1길',
 '대평3길',
 '대평로',
 '도봉구',
 '도움1로',
 '도움3로',
 '도움6로',
 '동구',
 '동대문구',
 '동두천시',
 '동래구',
 '동작구',
 '동해시',
 '마음로',
 '마음안1로',
 '마음안로',
 '마포구',
 '만남로',
 '목포시',
 '무안군',
 '무주군',
 '문경시',
 '미추홀구',
 '밀양시',
 '반곡로',
 '밝은뜰로',
 '보듬2로',
 '보듬3로',
 '보듬4로',
 '보람1길',
 '보람동로',
 '보람로',
 '보령시',
 '보성군',
 '보은군',
 '봉화군',
 '부강면',
 '부산진구',
 '부안군',
 '부여군',
 '부천시',
 '부평구',
 '북구',
 '사상구',
 '사천시',
 '사하구',
 '산청군',
 '삼척시',
 '상주시',
 '새롬남로',
 '새롬로',
 '새롬북로',
 '새롬중앙1로',
 '새롬중앙로',
 '서구',
 '서귀포시',
 '서대문구',
 '서산시',
 '서천군',
 '서초구',
 '성남시',
 '성동구',
 '성북구',
 '성주군',
 '세종로',
 '소담1로',
 '소담3로',
 '소담4로',
 '소담로',
 '소정면',
 '속초시',
 '송파구',
 '수성구',
 '수영구',
 '수원시',
 '순창군',
 '순천시',
 '시청대로',
 '시흥시',
 '신안군',
 '아름서1길',
 '아름서길',
 '아산시',
 '안동시',
 '안산시',
 '안성시',
 '안양시',
 '양구군',
 '양산시',
 '양양군',
 '양주시',
 '양천구',
 '양평군',
 '어울누리로',
 '여수시',
 '여주시',
 '연기면',
 '연동면',
 '연서면',
 '연수구',
 '연제구',
 '연천군',
 '영광군',
 '영덕군',
 '영도구',
 '영동군',
 '영등포구',
 '영암군',
 '영양군',
 '영월군',
 '영주시',
 '영천시',
 '예산군',
 '예천군',
 '오산시',
 '옥천군',
 '옹진군',
 '완도군',
 '완주군',
 '용산구',
 '용인시',
 '울릉군',
 '울주군',
 '울진군',
 '원주시',
 '유성구',
 '은평구',
 '음성군',
 '의령군',
 '의성군',
 '의왕시',
 '의정부시',
 '이천시',
 '익산시',
 '인제군',
 '임실군',
 '장군면',
 '장성군',
 '장수군',
 '장흥군',
 '전동면',
 '전의면',
 '전주시',
 '절재로',
 '정선군',
 '정읍시',
 '제주시',
 '제천시',
 '조치원읍',
 '종로구',
 '중구',
 '중랑구',
 '증평군',
 '진도군',
 '진안군',
 '진주시',
 '진천군',
 '집현동로',
 '집현서로',
 '창녕군',
 '창원시',
 '천안시',
 '철원군',
 '청도군',
 '청송군',
 '청양군',
 '청주시',
 '춘천시',
 '충주시',
 '칠곡군',
 '태백시',
 '태안군',
 '통영시',
 '파주시',
 '평창군',
 '평택시',
 '포천시',
 '포항시',
 '하남시',
 '하동군',
 '한누리대로',
 '함안군',
 '함양군',
 '함평군',
 '합천군',
 '해남군',
 '해밀3로',
 '해운대구',
 '호려울로',
 '홍성군',
 '홍천군',
 '화성시',
 '화순군',
 '화천군',
 '횡성군']

In [13]:
분당미용실 = 도로명.loc[도로명[1].astype("str").apply(lambda x: "분당" in x)]

In [14]:
분당미용실

Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]
Index: []

In [15]:
조치원미용실 = 도로명.loc[(도로명[0] == '세종특별자치시') & (도로명[1] == '조치원읍')]

In [16]:
조치원미용실

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
219129,세종특별자치시,조치원읍,새내로,"122,",메가박스,1층,110호,None,None,None,None,None,None,None,None,None,None,None
219232,세종특별자치시,조치원읍,죽림로,"45,",신동아아파트,제1단지,상가동,102호,None,None,None,None,None,None,None,None,None,None
219398,세종특별자치시,조치원읍,죽림로,"45,",신동아아파트,상가동,1층,112호,None,None,None,None,None,None,None,None,None,None
220044,세종특별자치시,조치원읍,세종로,"2282,",2층,229호,None,None,None,None,None,None,None,None,None,None,None,None
220785,세종특별자치시,조치원읍,세종로,"2282,",럭스스퀘어,2층,221(우측)호,None,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
380723,세종특별자치시,조치원읍,새내8길,"23,",1층,None,None,None,None,None,None,None,None,None,None,None,None,None
381392,세종특별자치시,조치원읍,허만석로,"60,",홈플러스,조치원점,2층,None,None,None,None,None,None,None,None,None,None,None
381775,세종특별자치시,조치원읍,새내10길,"64,",1층,None,None,None,None,None,None,None,None,None,None,None,None,None
390803,세종특별자치시,조치원읍,봉신길,"151,",2층,None,None,None,None,None,None,None,None,None,None,None,None,None
390804,세종특별자치시,조치원읍,봉신길,"151,",2층,None,None,None,None,None,None,None,None,None,None,None,None,None

In [83]:
def icontains(keyword):
    return lambda a : keyword in a
def series_contains(series, keyword):
    return series.astype("str").apply(icontains(keyword))
def iter_series_contains(iter, keyword, iter_count):
    return [series_contains(iter[i], keyword) for i in range(iter_count)]
def iterOR(iter):
    default = iter[0]
    for it in iter[1:]:
        default = default | it
    return default

def iter_series_contains_or(iter, keyword, iter_count):
    return iterOR(iter_series_contains(iter, keyword, iter_count))

def iterOR_func(iter, func):
    default = iter[0].astype("str").apply(func)
    for it in iter[1:]:
        default = default | it.astype("str").apply(func)
    return default

In [88]:
분당미용실 = 도로명.loc[iterOR_func([도로명[i] for i in range(3)], icontains("분당"))]
별내미용실 = 도로명.loc[iterOR_func([도로명[i] for i in range(3)], icontains("별내"))]
중계미용실 = 도로명.loc[iterOR_func([도로명[i] for i in range(3)], icontains("중계"))]
강남미용실 = 도로명.loc[iterOR_func([도로명[i] for i in range(3)], icontains("강남")) & 도로명[0].astype("str").apply(icontains("서울특별시"))]
조치원미용실 = 도로명.loc[iter_series_contains_or(도로명, "조치원", 3) & iter_series_contains_or(도로명, "세종", 1)]

In [89]:
조치원미용실

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
219129,세종특별자치시,조치원읍,새내로,"122,",메가박스,1층,110호,None,None,None,None,None,None,None,None,None,None,None
219232,세종특별자치시,조치원읍,죽림로,"45,",신동아아파트,제1단지,상가동,102호,None,None,None,None,None,None,None,None,None,None
219398,세종특별자치시,조치원읍,죽림로,"45,",신동아아파트,상가동,1층,112호,None,None,None,None,None,None,None,None,None,None
220044,세종특별자치시,조치원읍,세종로,"2282,",2층,229호,None,None,None,None,None,None,None,None,None,None,None,None
220785,세종특별자치시,조치원읍,세종로,"2282,",럭스스퀘어,2층,221(우측)호,None,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
380723,세종특별자치시,조치원읍,새내8길,"23,",1층,None,None,None,None,None,None,None,None,None,None,None,None,None
381392,세종특별자치시,조치원읍,허만석로,"60,",홈플러스,조치원점,2층,None,None,None,None,None,None,None,None,None,None,None
381775,세종특별자치시,조치원읍,새내10길,"64,",1층,None,None,None,None,None,None,None,None,None,None,None,None,None
390803,세종특별자치시,조치원읍,봉신길,"151,",2층,None,None,None,None,None,None,None,None,None,None,None,None,None
390804,세종특별자치시,조치원읍,봉신길,"151,",2층,None,None,None,None,None,None,None,None,None,None,None,None,None

In [69]:
분당미용실

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
219007,경기도,성남시,분당구,성남대로926번길,"6,",야탑,대덕프라자,6층,612호,(야탑동),None,None,None,None,None,None,None,None
219185,경기도,성남시,분당구,분당로,"326,",분당동근린빌딩,1층,일부,(분당동),None,None,None,None,None,None,None,None,None
219186,경기도,성남시,분당구,판교로,"441,",남서울프라자,1층,105호,(야탑동),None,None,None,None,None,None,None,None,None
219223,경기도,성남시,분당구,수내로,"39,",비주거시설동,1층,127호,(수내동),None,None,None,None,None,None,None,None,None
219224,경기도,성남시,분당구,판교대장로6길,"10,",2층,"201호,202호",(대장동),None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
382299,경기도,성남시,분당구,장미로,"198,",아델파크빌,지하1층,B110-1호,(야탑동),None,None,None,None,None,None,None,None,None
382311,경기도,성남시,분당구,성남대로,"151,",분당엠코헤리츠,2층,219호,(구미동),None,None,None,None,None,None,None,None,None
382328,경기도,성남시,분당구,정자일로,"30,",청솔마을,상가동,1층,103호,(금곡동),None,None,None,None,None,None,None,None
382332,경기도,성남시,분당구,내정로,"24,",상가동,1층,106호,"(정자동,",정든마을한진6단지아파트),None,None,None,None,None,None,None,None
382428,경기도,성남시,분당구,서현로,"170,",풍림아이원플러스,2층,216-2호,일부호,(서현동),None,None,None,None,None,None,None,None

In [70]:
별내미용실

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
219539,경기도,남양주시,별내면,청학로132번길,"21,",주1동,1층,(오렌지하우스),None,None,None,None,None,None,None,None,None,None
220979,경기도,남양주시,별내5로5번길,"25,",1층일부,(별내동),None,None,None,None,None,None,None,None,None,None,None,None
221207,경기도,남양주시,별내중앙로,"53,",2층,"202,203호",(별내동),None,None,None,None,None,None,None,None,None,None,None
221497,경기도,남양주시,별내중앙로,"10,",별내역,아이파크,스위트,229호,(별내동),None,None,None,None,None,None,None,None,None
222594,경기도,남양주시,별내5로5번길,"4-20,",1층,일부,(별내동),None,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
380120,경기도,남양주시,별내5로5번길,"15,",1층,일부,(별내동),None,None,None,None,None,None,None,None,None,None,None
380519,경기도,남양주시,별내중앙로,"50,",청운프라자,3층,일부,(별내동),None,None,None,None,None,None,None,None,None,None
381288,경기도,남양주시,별내5로23번길,"6,",1층,일부호,(별내동),None,None,None,None,None,None,None,None,None,None,None
381752,경기도,남양주시,별내면,청학로중앙길,"15,",주공프라자,상가동,207호,None,None,None,None,None,None,None,None,None,None
382260,경기도,남양주시,별내3로,"64-7,",플레티넘예스,402호,(별내동),None,None,None,None,None,None,None,None,None,None,None

In [73]:
강남미용실

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
218960,서울특별시,강남구,강남대로152길,"64,",5층,501호,(신사동),None,None,None,None,None,None,None,None,None,None,None
219057,서울특별시,서초구,강남대로83길,"58,",1층,101호,(반포동),None,None,None,None,None,None,None,None,None,None,None
219058,서울특별시,서초구,강남대로,"589,",1동,지하1층,N105호,(잠원동),None,None,None,None,None,None,None,None,None,None
219130,서울특별시,강남구,언주로174길,"22,",지상2층,(신사동),None,None,None,None,None,None,None,None,None,None,None,None
219131,서울특별시,강남구,압구정로30길,"23,",지상3층,305호,(신사동),None,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
385775,서울특별시,서초구,강남대로,"221,",104호,(양재동),None,None,None,None,None,None,None,None,None,None,None,None
385779,서울특별시,서초구,강남대로,"222-4,",3층,"(양재동,",메디컬빌딩),None,None,None,None,None,None,None,None,None,None,None
386123,서울특별시,서초구,강남대로83길,"48-3,",1층,(반포동),None,None,None,None,None,None,None,None,None,None,None,None
386125,서울특별시,서초구,강남대로107길,"6,",1동,3층,"(잠원동,",더리버사이드호텔),None,None,None,None,None,None,None,None,None,None
386605,서울특별시,서초구,강남대로85길,"21-12,",102호,(반포동),None,None,None,None,None,None,None,None,None,None,None,None

In [67]:
중계미용실

Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]
Index: []